### ISSUE TITLE
Pod don't start after delete.

### ISSUE THREAD

**Issue by chemist** [embercsi/ember-csi#157]
I install ember-csi on k8s 1.17, centos 7, only lvm and iscsi (clean system, k8s installed with kubeadm)

And I see next problem, when I made "kubectl delete pod csi-node-***, it can't restart any more.
It always crashes.

After reboot node, it starts.
I attach log from 1 node here.

I found that this problem because of /dev/termination-log
```bash
systemctl stop docker containerd Kubelet
umount /dev/termination-log
systemctl start docker kubelet
 ```
after it all starts.

I add to ds 
`terminationMessagePath: /tmp/termination-csi`
it helps, now I don't have any problem with permanent crashes.

[log here](https://github.com/embercsi/ember-csi/files/4185514/csi-error.txt)

**Comment by Akrog** [comment]
Thanks for reporting the issue and the solution!
We'll update the examples and the operator.

**Comment by Akrog** [comment]
The operator is already [doing the right thing the right thing](https://github.com/embercsi/ember-csi-operator/blob/4024d6cc3eba3d2b10cd424745199e8805385a85/pkg/controller/embercsi/node.go#L142), so this is just a problem with this repository's example:

```
			TerminationMessagePath: "/tmp/termination-log",
```
