### ISSUE TITLE
Snapshot volume beta API

### ISSUE THREAD

**Issue by awels** [embercsi/ember-csi#159]
Currently ember installs the alpha volume snapshot api, which has been deprecated in kubernetes 1.17 and no longer supported in openshift. Please install the betav1 api when the controller is started.

**Comment by Akrog** [comment]
Are you referring to the `VolumeSnapshotClass` in the [1.16 Kubernetes example](https://github.com/embercsi/ember-csi/blob/master/examples/k8s_v1.16-CSI_v1.1/kubeyml/lvm/04-snapshot-class.yml)?

OpenShift 4.3 supports `snapshot.storage.k8s.io/v1alpha1`, it is 4.4 that doesn't support it.

Yes we need to update the examples to support K8s versions higher than 1.16.

**Comment by awels** [comment]
Yes, but it appears the controller actually installs some CRDs (it has the cluster role to do so, which is probably not something we want the controller to do).

```
$ kubectl get crd
NAME                                             CREATED AT
volumesnapshotclasses.snapshot.storage.k8s.io    2020-03-11T18:26:37Z <-- is from example
volumesnapshotcontents.snapshot.storage.k8s.io   2020-03-11T18:26:37Z <-- controller?
volumesnapshots.snapshot.storage.k8s.io          2020-03-11T18:26:37Z <-- controller?
```
I am not entirely sure what installs the other two crds

**Comment by Akrog** [comment]
The other 2 are most likely created by the `snapshotter` sidecar because the wrong sidecar is being used.
Kubernetes v1.17 needs a different snapshotter sidecar.
For K8s v1.16 or is v1.y.z of the sidecar, and K8s is v2.y.z ([reference](https://kubernetes-csi.github.io/docs/external-snapshotter.html))

**Comment by awels** [comment]
Gotcha, so I just need to update the yaml to use the correct side car. I grepped the project and I couldn't find anything creating them. But the side car makes sense.
