### ISSUE TITLE
StorageBackend vSphere Failed as Operator in OKD 4.5

### ISSUE THREAD

**Issue by creativie** [embercsi/ember-csi#167]
OKD 4.5 beta (Fedora CoreOS)
Ember-csi operator

When I add new storage backend with vsphere driver all pod become failing
```
Error: container create failed: time="2020-06-24T06:40:26Z" level=warning msg="exit status 1" time="2020-06-24T06:40:26Z" level=error msg="container_linux.go:349: starting container process caused \"process_linux.go:449: container init caused \\\"rootfs_linux.go:58: mounting \\\\\\\"/etc/localtime\\\\\\\" to rootfs \\\\\\\"/var/lib/containers/storage/overlay/c87616da1d0f51f436eacf9e97bc4622c0285aad28edbcc08a1ec7283d7f930c/merged\\\\\\\" at \\\\\\\"/var/lib/containers/storage/overlay/c87616da1d0f51f436eacf9e97bc4622c0285aad28edbcc08a1ec7283d7f930c/merged/usr/share/zoneinfo/UTC\\\\\\\" caused \\\\\\\"not a directory\\\\\\\"\\\"\"" container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/etc/localtime\\\" to rootfs \\\"/var/lib/containers/storage/overlay/c87616da1d0f51f436eacf9e97bc4622c0285aad28edbcc08a1ec7283d7f930c/merged\\\" at \\\"/var/lib/containers/storage/overlay/c87616da1d0f51f436eacf9e97bc4622c0285aad28edbcc08a1ec7283d7f930c/merged/usr/share/zoneinfo/UTC\\\" caused \\\"not a directory\\\"\""
```

I delete volume '/etc/localtime' from statefulset and daemon, after pods starts successfully

**Comment by Akrog** [comment]
@creativie thanks for the report.

I believe the reason for the failure is that the hosts are missing the `/etc/localtime` file, so the container engine when detects that it's missing the source path creates a directory (I believe this is the default behavior for the engines I know) and then proceeds to do the binding, but then the binding finds that we are trying to bind a directory (the one created by the engine) with a normal file that exists within the container and fails with the error we see.

As far as I know your hosts should have `/etc/localtime`. Could you confirm what do you have on your host's `/etc/localtime` path please?

**Comment by creativie** [comment]
No
```
ls: cannot access '/etc/localtime': No such file or directory
```
