### ISSUE TITLE
Use ConfigMap to store backend storage credentials

### ISSUE THREAD

**Issue by thiagodasilva** [embercsi/ember-csi#17]
The backend storage crendentials are currently listed in the csi driver manifest, we should use ConfigMaps to store them securely and separate that data from the manifest itself...

**Comment by kirankt** [comment]
I think a better approach would be to use secrets as opposed to configmaps but the general idea is the same: separate credentials from the template.

**Comment by Akrog** [comment]
We pass this responsibility to the operator, which is using secrets to pass the configuration.
