### ISSUE TITLE
CSI 1.0 Driver name should be forward domain notation

### ISSUE THREAD

**Issue by saad-ali** [embercsi/ember-csi#92]
Per the [CSI spec](https://github.com/container-storage-interface/spec/blob/master/spec.md#getplugininfo) the name of a CSI driver must conform to the following requirements:

```
The name MUST follow domain name notation format (https://tools.ietf.org/html/rfc1035#section-2.3.1).

It SHOULD include the plugin's host company name and the plugin name, to minimize the possibility of collisions.

It MUST be 63 characters or less, beginning and ending with an alphanumeric character ([a-z0-9A-Z]) with dashes (-), dots (.), and alphanumerics between.

This field is REQUIRED.
```
CSI 0.x required reverse domain notation. But [CSI 1.0](https://github.com/container-storage-interface/spec/releases/tag/v1.0.0) dropped the "reverse" part of the requirement. The expectation is that the name will be normal (forward) domain notation.

So for CSI 1.0, instead of `io.ember-csi.[x]` the driver name should be `[x].ember-csi.io`

**Comment by Akrog** [comment]
Thanks @saad-ali, good catch!
We'll change it to do reverse notation when running with v0.2 and v0.3 and forward notation for v1.0.
Re-reading that section of the spec I wonder if the 63 characters or less is referring to the rfc1035 length restriction of `label` or if it refers to the fact that `name` must not be longer than 63 chars.

**Comment by saad-ali** [comment]
Intention is "`name` must not be longer than 63 chars" so that it can be used as a prefix for a label by the CO.

**Comment by Akrog** [comment]
Thanks, I updated the PR to also enforce the max 63 chars for the whole name, instead of just 63 max for each `label` as described in rfc1035
